site_name: Fresh Bakery
site_description: Lightweight dependency injection framework

theme:
    name: 'material'

repo_name: mityuha/fresh-bakery
repo_url: https://github.com/mityuha/fresh-bakery

nav:
    - Introduction: 'index.md'
    - Baking Methods: 'baking_methods.md'

markdown_extensions:
  - mkautodoc
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
