name: fresh-bakery CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: "${{ matrix.runs-on || 'ubuntu-latest' }}"
    strategy:
      matrix:
        include:
          - { python-version: "3.6", runs-on: "ubuntu-20.04" }
          - { python-version: "3.7" }
          - { python-version: "3.8" }
          - { python-version: "3.9" }
          - { python-version: "3.10" }
          - { python-version: "3.11" }

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions
      - name: Run tox
        run: tox

